### ISSUE TITLE
JS SIP lib

### ISSUE THREAD

**Issue by piejanssens** [jimhigson/ring-api#1]
FYI http://jssip.net/documentation/3.1.x/overview/

**Comment by jimhigson** [comment]
I have seen this but I don’t know very much about SIP. I’d very much like to get streaming video working. Do you know how to connect to a stream given the data coming from ring? I tried a few different ways but found that it was failing silently most of the time

**Comment by jimhigson** [comment]
Also, jssip seems to be for sip over websockets. Do you know if ring uses ws?

**Comment by piejanssens** [comment]
No I don't, I just came across the jssip library and thought it might interest you.
Have you seen this? It shows some details on the SIP protocol being used.
You can see in one of the packets that there is info on the RTP stream. That's where the money's at.

**Comment by jimhigson** [comment]
I have seen that yes. The tricky part seems to be actually getting a ja sip client to connect.

Drachito looks promising but the server-side part of it didn’t build nicely for me on the first few tries

**Comment by rosswaycaster** [comment]
So is there currently no way to view the Ring’s live video stream?

**Comment by jimhigson** [comment]
You can get the SIP data using this API, and pass that to a SIP client, but
there’s no automatic “show me a stream” function

**Comment by WeldFire** [comment]
Do you have a recommendation for SIP clients that work with the Ring data? 
From the ones that I've downloaded I don't understand how to translate the data provided by your API to the SIP client parameters.

**Comment by jimhigson** [comment]
I haven’t actually gotten a stream showing because it wasn’t needed for the
project I originally made this for. I’d be really interested to hear from
anyone who got it from the API to video pixels on the screen - would
definitely add an example script to the project

**Comment by jimhigson** [comment]
I guess from here the best course of action might be to show the js-sip
support chat/issues/whatever what you’re getting from this API and ask how
they’d use that to show an image on the screen. SIP is a pretty weird
looking protocol to people used to rest and websockets

**Comment by AppleTechy** [comment]
I have yet to get video working. If I had to take a guess the SIP credentials are only valid for the device that requested them and that they are only allow a connection to be established within a couple seconds before the credentials are invalid. Here is the research I did a year ago (held off on publishing it online since I didn't want it to get changed on me before I implemented it into anything). 
https://github.com/AppleTechy/Ring. I tested both via their MacOs app and IOS app and API calls seemed to be the same, I however I never got around to confirming the SIP info on the iPhone. I can also provide a non protected version of the ring's IOS app(disassembled)  if that would help you. The best thing I came across was RTMPdump in combination with FFMPEG to display everything...

**Comment by bourdakos1** [comment]
I don't know if this is helpful, but I'm able to pull ~30 seconds of video stream using the node module `sip`, it was quite the headache to get everything working and it's not perfect, but I have a demo script that outputs .h264 files which you can convert to mp4 https://github.com/bourdakos1/ring-streamer

**Comment by dgreif** [comment]
@bourdakos1 just a heads up, this project is not longer being maintained by @jimhigson.

As for your ring-streamer library, it's pretty cool that you were able to take the UDP and pipe it out to a usable file.  What's not cool is that you copy and pasted my code without any credit back to myself of my repo.  I know that it is open source, but common courtesy would be to at least say where 50% of your code came from.  I intentionally exposed the `createSipSession` method on each camera to make it easy for developers to make add-ons like yours.  I would appreciate it if you could pull my package in as a dependency and use it the right way.  If you need any changes made to make things easier (such as setting up the local ports, etc.), I would be happy to take a pull request so that everyone can benefit from the changes.  You seem to have a good grasp on RTP so I would appreciate your help to improve my api, rather than having you spin it off as your own.

**Comment by bourdakos1** [comment]
@dgreif ah sorry about that, can you link me to the repo I lost it somewhere along the rabbit hole

**Comment by bourdakos1** [comment]
🤦‍♂️ it's on your profile haha https://github.com/dgreif/ring

**Comment by bourdakos1** [comment]
@dgreif I was able to get it working using you SipSession, but I'm not able to successfully get the sip info from you api, so I'm still using `ring-api` for that. Should I open an issue on your repo?
